add delay(10min) and check stream_type is live
Accropolis/brower-extension pull request #2
Opened 2018-04-04 23:01 UTC by nspu

change timeout to interval

2018-04-26 19:03 UTC, JeremiePat requested changes
GG :) Ça fait le job correctement.

Par contre, y'a deux truc qui ne me mettent pas très à l'aise. Est-ce que tu peux regarder pour changer ça avant de merger?

2018-04-26 19:03 UTC, JeremiePat commented on main.js
> +          timeout = setTimeout(onLiveChange, time)
`timeout` n'est définie nule part! On créer donc une variable globale à la première assignation. Ce serait bien d'éviter ça.

2018-04-26 19:03 UTC, JeremiePat commented on main.js
> +  interval = setInterval(onLiveChange, REFRESH_TIME)
Je ne suis pas du tout d'accord avec l'utilisation de setInterval. C'est une fonction qui peut amener plein de problème (ok, c'est très peu probable dans ce cas, même si 'lusage d'un setTimeout qui appel onLiveChange en même temps que setInterval qui fait la même chose n'est pas rassurant du tout... y'a un risque de voir les deux appel de fonction se marcher sur le pied bizzarement). C'est toujours plus sur d'utiliser setTimeout de manière récursive comme c'était le cas avant plutot que setInterval (et surtout le mélange des deux, c'est dangeureux). Est-ce qu'on pourrai revenir a ce qui était fait avant ou bien il y a une contrainte qui l'empèche?

2018-04-26 19:50 UTC, nspu commented on main.js
> +          timeout = setTimeout(onLiveChange, time)
Ha oui, je l'avais déclaré en tant que global l15. Mais de tout façon je vais la supprimer.

2018-04-26 19:51 UTC, nspu commented on main.js
> +  interval = setInterval(onLiveChange, REFRESH_TIME)
Okay je ne savais pas, je vais change ça.

2018-05-04 08:19 UTC, JeremiePat approved these changes

2018-05-04 08:19 UTC, JeremiePat commented
Nickel, en plus le code est plus simple. C'est mergé :)

2018-05-04 08:19 UTC, merged

2018-05-04 08:27 UTC, JeremiePat commented
Ok, j'ai taggué une nouvelle version (1.2.0)
Il va falloir s'occuper du déploiement sur les stores maintenant (l'extension zippée qui va bien: https://github.com/Accropolis/brower-extension/releases/download/1.2.0/accropolis-extension.zip)

Je pense qu'il n'y a que Sylvain qui à les droits pour ça. Je te laisse le pinger.